version: '3'

services:
  postgres:
    container_name: cornucopia-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Asdf1234
    volumes:
      - ./data:/docker-entrypoint-initdb.d